apiVersion: v1
kind: Service
metadata:
  name: simple-reverse-proxy-svc
  labels:
    service: simple-reverse-proxy-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: simple-reverse-proxy
  type: LoadBalancer